#### Basic array creation


In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5]) 
arr

array([1, 2, 3, 4, 5])

In [8]:
a =  [1, 2, 3, 4, 5.]
np.array(a)

array([1., 2., 3., 4., 5.])

In [14]:
l = [1, 2,3 ] , [3, 4, 5]
l


([1, 2, 3], [3, 4, 5])

In [15]:
np.array(l)

array([[1, 2, 3],
       [3, 4, 5]])

#### array generation function


In [19]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [22]:
arr = np.zeros((3, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
arr = np.linspace(1, 5, 3)
arr

array([1., 3., 5.])

#### Random generation function

In [28]:
np.random.rand(3, 3)

array([[0.61211074, 0.33820745, 0.62196148],
       [0.68956367, 0.0318115 , 0.92320434],
       [0.25942094, 0.07072781, 0.73574748]])

In [29]:
np.random.randn(10)

array([ 1.82145693,  0.54544652,  0.58084358,  1.3211944 ,  1.77996381,
       -0.33028211, -0.07549184,  1.3322729 ,  1.75446927,  0.14754895])

In [32]:
np.random.randint(10, 20, 10)

array([16, 15, 14, 16, 13, 13, 17, 17, 17, 16], dtype=int32)

#### Array attributes

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr.shape

(3, 3)

In [36]:
arr.size

9

In [37]:
arr.dtype

dtype('int64')

#### Array method

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr.min()


np.int64(1)

In [44]:
arr.max()

np.int64(9)

In [45]:
arr.sum()

np.int64(45)

In [48]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [49]:
arr.mean()

np.float64(5.0)

In [50]:
arr.std()

np.float64(2.581988897471611)

In [51]:
arr.argmax()

np.int64(8)

In [52]:
arr.argmin()

np.int64(0)

#### Reshaping and resizing

In [55]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [56]:
arr.reshape(6, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### NUMPY INDEXING AND SLICING OF VECTORS

In [60]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [61]:
arr[1:5]

array([12, 13, 14, 15])

In [64]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [66]:
arr[4]

np.int64(15)

### NUMPY INDEXING AND SLICING OF MATRIX

In [68]:
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [70]:
arr[1, 1]

np.int64(7)

In [71]:
arr[0:2, 1:3]

array([[2, 3],
       [7, 8]])

In [75]:
arr[3:, 3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [77]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

### BOOLEAN INDEXING

In [78]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [79]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [80]:
arr = arr [bool_index]
arr

array([12, 14, 16, 18, 20])

## Array operation

#### arithmetic operation

In [81]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
a1

array([1, 2, 3])

In [82]:
a1+ a2

array([5, 7, 9])

In [83]:
a1-a2

array([-3, -3, -3])

In [84]:
a1 / a2

array([0.25, 0.4 , 0.5 ])

In [85]:
a1 // a2

array([0, 0, 0])

#### deep and shallow copy

In [88]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [91]:
slice = a[:5]
slice = slice *2
slice

array([ 2,  4,  6,  8, 10])

In [92]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [101]:
#deepcopy
a
b=a

In [95]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [96]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#shallow copy
b= a.copy()
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [99]:
b[0] = 100
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [100]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### Matrix operations

In [104]:
A = np.array([[1, 2 ], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [105]:
A

array([[1, 2],
       [3, 4]])

In [106]:
B


array([[5, 6],
       [7, 8]])

In [107]:
A*B

array([[ 5, 12],
       [21, 32]])

In [108]:
A@B

array([[19, 22],
       [43, 50]])

In [109]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [110]:
A

array([[1, 2],
       [3, 4]])

In [111]:
A.T

array([[1, 3],
       [2, 4]])

### Adavance array manipulation

#### stacking array

In [115]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [117]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [119]:
np.column_stack((a, b)) 

array([[1, 4],
       [2, 5],
       [3, 6]])

#### splitting array

In [121]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [122]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [124]:
a =np.vsplit(c, 2)


In [125]:
for i in a:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
